# Generated by Django 5.1.8 on 2026-04-23 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('periodo_desde', models.DateField()),
                ('periodo_hasta', models.DateField()),
                ('gastos_periodo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_sin_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_con_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adeudado_final', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada_parcial', 'Pagada parcialmente'), ('pagada', 'Pagada')], default='pendiente', max_length=20)),
                ('factura', models.CharField(blank=True, max_length=100)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='maestros.proveedor')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Preliquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('periodo_desde', models.DateField()),
                ('periodo_hasta', models.DateField()),
                ('gastos_periodo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_sin_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_con_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adeudado_final', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmada', 'Confirmada'), ('liquidada', 'Liquidada')], default='borrador', max_length=15)),
                ('liquidacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preliquidaciones', to='operaciones.liquidacion')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preliquidaciones', to='maestros.proveedor')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('remito', models.PositiveIntegerField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='maestros.cliente')),
                ('liquidacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes', to='operaciones.liquidacion')),
                ('preliquidacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes', to='operaciones.preliquidacion')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='maestros.proveedor')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='maestros.salida')),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='maestros.tarifa')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PreliquidacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_viaje', models.DateField()),
                ('chofer_snapshot', models.CharField(blank=True, max_length=150)),
                ('cliente_snapshot', models.CharField(max_length=150)),
                ('salida_snapshot', models.CharField(max_length=200)),
                ('remito_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('adicionales_snapshot', models.JSONField(blank=True, default=list)),
                ('tarifa_sin_iva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tarifa_con_iva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('adeudado_parcial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('preliquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='operaciones.preliquidacion')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preliquidacion_detalles', to='operaciones.viaje')),
            ],
            options={
                'unique_together': {('preliquidacion', 'viaje')},
            },
        ),
        migrations.CreateModel(
            name='LiquidacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_viaje', models.DateField()),
                ('chofer_snapshot', models.CharField(blank=True, max_length=150)),
                ('cliente_snapshot', models.CharField(max_length=150)),
                ('salida_snapshot', models.CharField(max_length=200)),
                ('remito_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('adicionales_snapshot', models.JSONField(blank=True, default=list)),
                ('tarifa_sin_iva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tarifa_con_iva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('adeudado_parcial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='operaciones.liquidacion')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidacion_detalles', to='operaciones.viaje')),
            ],
            options={
                'unique_together': {('liquidacion', 'viaje')},
            },
        ),
        migrations.CreateModel(
            name='ViajeAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_snapshot', models.CharField(max_length=150)),
                ('precio_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('adicional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='maestros.adicional')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adicionales', to='operaciones.viaje')),
            ],
            options={
                'unique_together': {('viaje', 'adicional')},
            },
        ),
    ]
