# Generated by Django 5.1.8 on 2026-04-26 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0001_initial'),
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('habilitado', 'Habilitado'), ('preliquidado', 'Preliquidado'), ('liquidado', 'Liquidado')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_gasto', models.DateField()),
                ('varios', models.JSONField(blank=True, default=list, help_text='Lista de {descripcion, monto}')),
                ('adelanto_otros', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('combustible', models.JSONField(blank=True, default=dict, help_text='{lts_comb, precio_lts_comb, precio_total_comb}')),
                ('remito_combustible', models.CharField(blank=True, max_length=100)),
                ('liquidacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='operaciones.liquidacion')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='maestros.proveedor')),
            ],
            options={
                'ordering': ['-fecha_gasto'],
            },
        ),
    ]
