# Generated by Django 5.1.8 on 2026-04-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_viaje_estado_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='remito',
            field=models.PositiveIntegerField(blank=True, max_length=20, null=True),
        ),
    ]
