# Generated by Django 5.1.8 on 2026-04-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_alter_viaje_remito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='remito',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
