# Generated by Django 5.1.8 on 2026-04-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0005_alter_viaje_remito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidaciondetalle',
            name='remito_snapshot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='preliquidaciondetalle',
            name='remito_snapshot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
