# Generated by Django 5.1.8 on 2026-04-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0006_alter_remito_snapshot_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='combustible',
            field=models.JSONField(blank=True, default=dict, help_text='{lts_comb, precio_lts_comb, precio_total_comb}', null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='remito_combustible',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='varios',
            field=models.JSONField(blank=True, default=list, help_text='Lista de {descripcion, monto}', null=True),
        ),
        migrations.AlterField(
            model_name='liquidaciondetalle',
            name='adicionales_snapshot',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='preliquidaciondetalle',
            name='adicionales_snapshot',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
