# Generated by Django 5.1.8 on 2026-04-29 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0007_alter_gasto_combustible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='preliquidacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='operaciones.preliquidacion'),
        ),
        migrations.AlterField(
            model_name='preliquidacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('para_revisar', 'Para revisar'), ('confirmada', 'Confirmada'), ('liquidada', 'Liquidada')], default='pendiente', max_length=15),
        ),
    ]
