# Generated by Django 5.1.8 on 2026-04-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0008_unique_remito_fecha_proveedor'),
        ('operaciones', '0009_viajeadicional_descripcion_snapshot'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='viaje',
            constraint=models.UniqueConstraint(condition=models.Q(('remito__isnull', False), models.Q(('remito', ''), _negated=True)), fields=('remito', 'fecha', 'proveedor'), name='unique_remito_fecha_proveedor'),
        ),
    ]
