# Generated by Django 5.1.8 on 2026-05-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0010_unique_remito_fecha_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='preliquidacion',
            name='enviado_a_drive',
            field=models.BooleanField(default=False),
        ),
    ]
