[phases.setup]
nixPkgs = [
  "python312",
  "glib",
  "pango",
  "harfbuzz",
  "gdk-pixbuf",
  "cairo",
  "gobject-introspection",
  "fontconfig",
  "freetype",
  "libgobject-2.0",
]

[phases.install]
cmds = [
  "python3 -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install -r requirements.txt",
]
