# Generated by Django 5.1.8 on 2026-04-23 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cuit', models.CharField(max_length=13, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('chofer', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('categoria', models.CharField(choices=[('3ero_sin_semi', '3ero SIN SEMI'), ('1', 'Categoría 1'), ('2', 'Categoría 2'), ('3', 'Categoría 3')], max_length=20)),
                ('datos_transporte', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ida', models.CharField(max_length=100)),
                ('vuelta', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['ida', 'vuelta'],
                'unique_together': {('ida', 'vuelta')},
            },
        ),
        migrations.CreateModel(
            name='Adicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('precio_cat_3ero_sin_semi', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_cat_1', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_cat_2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_cat_3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adicionales', to='maestros.cliente')),
            ],
            options={
                'ordering': ['nombre', 'cliente', '-version'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('nombre', 'cliente'), name='unique_adicional_activo_por_nombre_cliente')],
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_cat_3ero_sin_semi', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_cat_1', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_cat_2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_cat_3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifas', to='maestros.cliente')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifas', to='maestros.salida')),
            ],
            options={
                'ordering': ['salida', 'cliente', '-version'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('salida', 'cliente'), name='unique_tarifa_activa_por_salida_cliente')],
            },
        ),
    ]
