# Generated by Django 5.1.8 on 2026-04-28 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salida',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='salida',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='maestros.cliente'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='salida',
            unique_together={('ida', 'vuelta', 'cliente')},
        ),
    ]
