# Generated by Django 5.1.8 on 2026-04-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0003_alter_cliente_cuit_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='datos_transporte',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
