# Generated by Django 5.1.8 on 2026-04-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0004_alter_proveedor_datos_transporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='carpeta_drive_id',
            field=models.CharField(blank=True, help_text='ID de carpeta en Google Drive', max_length=100, null=True),
        ),
    ]
