# Generated by Django 5.1.8 on 2026-04-29 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0007_adicional_cliente_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adicional',
            options={'ordering': ['nombre', '-version']},
        ),
    ]
