# Generated by Django 5.1.8 on 2026-04-29 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('maestros', '0005_proveedor_carpeta_drive_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='maestros.proveedor'),
        ),
    ]
